
import React from 'react';

export const TSuzuli = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p ><a href="https://t.co/qkWL8WnrYs">https://t.co/qkWL8WnrYs</a></p>&mdash; 初夏の夜風の涼しさ (@enkaust) <a href="https://twitter.com/enkaust/status/1507949606315110404?ref_src=twsrc%5Etfw">March 27, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);

// char 1
export const T20220202 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>【R-18🔞】skeb納品しました。リクエストありがとうございました！<a href="https://t.co/MUKQZBYvja">https://t.co/MUKQZBYvja</a> <a href="https://t.co/UlIjonaXpG">pic.twitter.com/UlIjonaXpG</a></p>&mdash; はいき｜𝗛𝗔𝗜𝗞𝗜 (@haiki396g) <a href="https://twitter.com/haiki396g/status/1488869489685012485?ref_src=twsrc%5Etfw">February 2, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20220107 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>Skebありがとうございました！<a href="https://t.co/sdYui5BcE1">https://t.co/sdYui5BcE1</a><a href="https://twitter.com/hashtag/Skeb?src=hash&amp;ref_src=twsrc%5Etfw">#Skeb</a> <a href="https://t.co/nSLnroOfRg">pic.twitter.com/nSLnroOfRg</a></p>&mdash; Pozon2🔞 (@Pozonuun) <a href="https://twitter.com/Pozonuun/status/1479281810123390978?ref_src=twsrc%5Etfw">January 7, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20211031 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>急遽描いたものですがこれでゆるしてくｄさい <a href="https://t.co/RI31p4pqZN">pic.twitter.com/RI31p4pqZN</a></p>&mdash; 司ろう。 (@shi46_u) <a href="https://twitter.com/shi46_u/status/1454814733920464900?ref_src=twsrc%5Etfw">October 31, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20210730 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://t.co/icTLFcsb59">https://t.co/icTLFcsb59</a></p>&mdash; 初夏の夜風の涼しさ (@sumiQj) <a href="https://twitter.com/sumiQj/status/1421131605460979718?ref_src=twsrc%5Etfw">July 30, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20210718 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>れんちゅ <a href="https://t.co/sG1zv9pJIJ">pic.twitter.com/sG1zv9pJIJ</a></p>&mdash; 絹豆腐📛 (@momentoufuR18) <a href="https://twitter.com/momentoufuR18/status/1416882380334243841?ref_src=twsrc%5Etfw">July 18, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20210715 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>? <a href="https://t.co/J2GFIIL8mm">pic.twitter.com/J2GFIIL8mm</a></p>&mdash; Totsuka (@ttqss) <a href="https://twitter.com/ttqss/status/1415714345334415360?ref_src=twsrc%5Etfw">July 15, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20210709 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://t.co/LWAQzq3tiw">pic.twitter.com/LWAQzq3tiw</a></p>&mdash; 初夏の夜風の涼しさ (@sumiqj) <a href="https://twitter.com/sumiqj/status/1413499483258638341?ref_src=twsrc%5Etfw">July 9, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20210627 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>skebで描かせてもらったよそ様のキャラ, めちゃ好みだったので楽しかった<br />残像ちんの修正がどうすればよいのか全然わからなかった, これも勉強ですね。。。 <a href="https://t.co/tsTvNadjCd">pic.twitter.com/tsTvNadjCd</a></p>&mdash; 🔞さぶこ (@sabu_ur) <a href="https://twitter.com/sabu_ur/status/1409123563672510469?ref_src=twsrc%5Etfw">June 27, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20210607 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://twitter.com/hashtag/lewd?src=hash&amp;ref_src=twsrc%5Etfw">#lewd</a> 盈君 <a href="https://t.co/rsJF0TLQMu">pic.twitter.com/rsJF0TLQMu</a></p>&mdash; 初夏の夜風の涼しさ (@sumiqj) <a href="https://twitter.com/sumiqj/status/1401933201350664197?ref_src=twsrc%5Etfw">June 7, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20210510 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>生首しか描けない <a href="https://t.co/Tb41nUC7wO">pic.twitter.com/Tb41nUC7wO</a></p>&mdash; 初夏の夜風の涼しさ (@sumiqj) <a href="https://twitter.com/sumiqj/status/1391770750495850498?ref_src=twsrc%5Etfw">May 10, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20210509 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>硯君納品頂いた! 有り難うございました!! <a href="https://t.co/oeXk9yIMRz">https://t.co/oeXk9yIMRz</a></p>&mdash; хлоод бризи ноцни лꙗта вчєсна (@sumiqj) <a href="https://twitter.com/sumiqj/status/1391332944501829633?ref_src=twsrc%5Etfw">May 9, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20210315 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>お待ｯｯｯｯｯｯｯｯたせしました！！！！！スプラッタホラー映画を見てる2人を納品させていただきましたー！！！ 楽しかったあ<br />ありがとうございました❣️<a href="https://t.co/jmW8NfkKzB">https://t.co/jmW8NfkKzB</a> <a href="https://twitter.com/hashtag/Skeb?src=hash&amp;ref_src=twsrc%5Etfw">#Skeb</a> <a href="https://twitter.com/hashtag/Commission?src=hash&amp;ref_src=twsrc%5Etfw">#Commission</a> <a href="https://twitter.com/skeb_jp?ref_src=twsrc%5Etfw">@skeb_jp</a>より <a href="https://t.co/X3cgkxsomH">pic.twitter.com/X3cgkxsomH</a></p>&mdash; たま魂👼 (@mkotan) <a href="https://twitter.com/mkotan/status/1371471958886391819?ref_src=twsrc%5Etfw">March 15, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20201230 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://t.co/57X83srnGH">https://t.co/57X83srnGH</a><br />素鉄（<a href="https://t.co/u94AW2qNF8">https://t.co/u94AW2qNF8</a>）先生に納品頂いた硯君, めっちゃ好い</p>&mdash; 初夏の夜風の涼しさ (@smiqy) <a href="https://twitter.com/enkaust/status/1344210173661835265?ref_src=twsrc%5Etfw">December 30, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20201210 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>skeb納品しましたーーー！！！！！リクエストありがとうございます！！！！！目隠れ髭は最高だな………今週の標語は「そのちんちん透けるよ」です<a href="https://t.co/qvVdZyiJ5e">https://t.co/qvVdZyiJ5e</a> <a href="https://twitter.com/hashtag/Skeb?src=hash&amp;ref_src=twsrc%5Etfw">#Skeb</a> <a href="https://twitter.com/hashtag/Commission?src=hash&amp;ref_src=twsrc%5Etfw">#Commission</a> <a href="https://twitter.com/skeb_jp?ref_src=twsrc%5Etfw">@skeb_jp</a>より <a href="https://t.co/kE4mOPkESK">pic.twitter.com/kE4mOPkESK</a></p>&mdash; たま魂👼 (@mkotan) <a href="https://twitter.com/mkotan/status/1337004643235160064?ref_src=twsrc%5Etfw">December 10, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20201208 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>納品しました　 <a href="https://t.co/nrDnzCPVB5">https://t.co/nrDnzCPVB5</a> <a href="https://t.co/E5f0pde8yt">pic.twitter.com/E5f0pde8yt</a></p>&mdash; 田中TAN (@l8TANNSFW) <a href="https://twitter.com/l8TANNSFW/status/1336289586549407745?ref_src=twsrc%5Etfw">December 8, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20201130 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>skeb納品させていただきました〜！！！！ありがとうございますイェイイェイ！！！！18禁！！！！！！！！！！！！ <a href="https://t.co/CZHF5sFImb">pic.twitter.com/CZHF5sFImb</a></p>&mdash; 肉駄🔞 (@nikuda2929) <a href="https://twitter.com/nikuda2929/status/1333099976650579973?ref_src=twsrc%5Etfw">November 29, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20201122 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://t.co/rBxQBfdM5S">https://t.co/rBxQBfdM5S</a><br />激辛拉麵🍜を食べる硯君を <a href="https://twitter.com/tino17_?ref_src=twsrc%5Etfw">@tino17_</a> さんに納品して頂きました!!<br />めっちゃかわいい……感謝……</p>&mdash; ſumı (@smiqy) <a href="https://twitter.com/enkaust/status/1330337966095544320?ref_src=twsrc%5Etfw">November 22, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20201021 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>共感を得られなかったグロかわ狼フード <a href="https://t.co/MxQJZq1Ls4">pic.twitter.com/MxQJZq1Ls4</a></p>&mdash; 絹豆腐📛 (@momentoufuR18) <a href="https://twitter.com/momentoufuR18/status/1318916428586627073?ref_src=twsrc%5Etfw">October 21, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20201009 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://twitter.com/TOS?ref_src=twsrc%5Etfw">@tos</a> 盈君 <a href="https://t.co/BbstJTFwK5">https://t.co/BbstJTFwK5</a> <a href="https://t.co/K5B93wGDQq">pic.twitter.com/K5B93wGDQq</a></p>&mdash; suzurı ıs my orıgınal character. (@smiqy) <a href="https://twitter.com/enkaust/status/1314648291636703232?ref_src=twsrc%5Etfw">October 9, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20201015 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>有り難う……神…………<a href="https://twitter.com/momentoufuR18?ref_src=twsrc%5Etfw">@momentoufuR18</a> <a href="https://t.co/ewEG9IIfod">pic.twitter.com/ewEG9IIfod</a></p>&mdash; ſumı (@smiqy) <a href="https://twitter.com/enkaust/status/1316746721121058817?ref_src=twsrc%5Etfw">October 15, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20201006 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://t.co/5UhCXe8lOG">pic.twitter.com/5UhCXe8lOG</a></p>&mdash; 墨幽 (@smiqy) <a href="https://twitter.com/enkaust/status/1313459340506853376?ref_src=twsrc%5Etfw">October 6, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20200909 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>身長差 (列べただけ) <a href="https://t.co/5rReHHdnqA">pic.twitter.com/5rReHHdnqA</a></p>&mdash; 初夏の夜風の涼しさ (@smiqy) <a href="https://twitter.com/enkaust/status/1303539039505506305?ref_src=twsrc%5Etfw">September 9, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20200822 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>後輩君の表情 考 <a href="https://t.co/I2JEPNS3nt">pic.twitter.com/I2JEPNS3nt</a></p>&mdash; 初夏の夜風の涼しさ (@smiqy) <a href="https://twitter.com/enkaust/status/1297245606977523712?ref_src=twsrc%5Etfw">August 22, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20200804 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>まあまあ上手くかけたと思う <a href="https://t.co/2U64U2EcRf">pic.twitter.com/2U64U2EcRf</a></p>&mdash; 絹豆腐📛 (@momentoufuR18) <a href="https://twitter.com/momentoufuR18/status/1290307240197386246?ref_src=twsrc%5Etfw">August 3, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20200731 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>🔞NFSW🔞<br />skeb納品しました！穴まで描きたかった〜〜〜〜ッ！<br />リクエストありがとうございました🌞<a href="https://t.co/cqMdrGNWyZ">https://t.co/cqMdrGNWyZ</a> <a href="https://t.co/kYUK5iYora">pic.twitter.com/kYUK5iYora</a></p>&mdash; たま魂👼 (@mkotan) <a href="https://twitter.com/mkotan/status/1289200726829195264?ref_src=twsrc%5Etfw">July 31, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20200724 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://twitter.com/sumimq?ref_src=twsrc%5Etfw">@sumimq</a> スミくんはぴば♥ <a href="https://t.co/LnbuWVojri">pic.twitter.com/LnbuWVojri</a></p>&mdash; 斎川 (@ti17_) <a href="https://twitter.com/ti17_/status/1286677524563365888?ref_src=twsrc%5Etfw">July 24, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20200710 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>Commission<a href="https://t.co/GCP58cuKd5">https://t.co/GCP58cuKd5</a> <a href="https://t.co/5sHvE7QLqa">pic.twitter.com/5sHvE7QLqa</a></p>&mdash; ミネむら (@minefarmkun) <a href="https://twitter.com/minefarmkun/status/1281632927529332736?ref_src=twsrc%5Etfw">July 10, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20200608 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>硯君 <a href="https://t.co/0DySjnl0jo">pic.twitter.com/0DySjnl0jo</a></p>&mdash; суми (@sumimq) <a href="https://twitter.com/sumimq/status/1270015188935172097?ref_src=twsrc%5Etfw">June 8, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20200530 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>完 <a href="https://t.co/sZA5QWL5K9">pic.twitter.com/sZA5QWL5K9</a></p>&mdash; СУМИ (@SumiMq) <a href="https://twitter.com/SumiMq/status/1266767231813214208?ref_src=twsrc%5Etfw">May 30, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20200424 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>リクエストありがとうございました～！Skeb(<a href="https://t.co/b5k3RNydjW">https://t.co/b5k3RNydjW</a> )にて, 納品完了です！ <br />※NSFW+18 <a href="https://t.co/GJ892FBly9">pic.twitter.com/GJ892FBly9</a></p>&mdash; 九磨🔞 (@9ma_param) <a href="https://twitter.com/9ma_param/status/1253513328783065088?ref_src=twsrc%5Etfw">April 24, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20200414 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>スズリ君の後輩君ことミツル君, この感じで行きます <a href="https://t.co/IzSj30XZYI">pic.twitter.com/IzSj30XZYI</a></p>&mdash; 𝔭𝔥𝔞𝔩𝔩𝔲𝔰, 𝔠𝔞𝔫𝔫𝔞𝔟𝔦𝔰, 𝔱𝔥𝔞𝔫𝔞𝔱𝔬𝔰 (@smgvn) <a href="https://twitter.com/smgvn/status/1250046521636085761?ref_src=twsrc%5Etfw">April 14, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20200413 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>skeb納品しました。ファーストリクエスト!ありがとうございました! R18NSFW <a href="https://t.co/CHKZMCC57p">https://t.co/CHKZMCC57p</a> <a href="https://t.co/ubMINM53hw">pic.twitter.com/ubMINM53hw</a></p>&mdash; T🔞 (@18TANNSFW) <a href="https://twitter.com/18TANNSFW/status/1249605824080539648?ref_src=twsrc%5Etfw">April 13, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20191004 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://twitter.com/melanophil?ref_src=twsrc%5Etfw">@melanophil</a> さんが生活物資支援してくれたからお礼に彼のオリキャラ(硯くん)のfanart描いた(これがパパ活)<br /><br />みんなも絹くん(180/73/21/大学生)にサポしてくれよな～ <a href="https://t.co/hA3AXsvwSy">pic.twitter.com/hA3AXsvwSy</a></p>&mdash; 絹豆腐 (@momentoufuR18) <a href="https://twitter.com/momentoufuR18/status/1180149743692812288?ref_src=twsrc%5Etfw">October 4, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20190926 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>うーんいない <a href="https://t.co/8lFhYofgu6">pic.twitter.com/8lFhYofgu6</a></p>&mdash; 司ろう。 (@shi46_u) <a href="https://twitter.com/shi46_u/status/1177286451647508480?ref_src=twsrc%5Etfw">September 26, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20190831 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>線画やる前に飽きちゃった…… (終)  <a href="https://t.co/M6klCWOTCN">pic.twitter.com/M6klCWOTCN</a></p>&mdash; 初夏の夜風の涼しさ (@sumigv) <a href="https://twitter.com/sumigv/status/1167690971410309120?ref_src=twsrc%5Etfw">August 31, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20190803 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://twitter.com/melanophil?ref_src=twsrc%5Etfw">@melanophil</a> めちゃくちゃ遅くなりまして申し訳ないのですがお誕生日おめでとうございます…！ happy birtday... <a href="https://t.co/0XZUjutoOi">pic.twitter.com/0XZUjutoOi</a></p>&mdash; 甘い酒 (@sweetZAKE) <a href="https://twitter.com/sweetZAKE/status/1157737672439320576?ref_src=twsrc%5Etfw">August 3, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20190718 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://t.co/tRtU7KUMdD">https://t.co/tRtU7KUMdD</a><a href="https://twitter.com/sikotamazou?ref_src=twsrc%5Etfw">@sikotamazou</a> 先生に依頼していたスズリ君が納品されました　最高に可愛い　文句無し　依頼して良かった</p>&mdash; ſumı (@smiqy) <a href="https://twitter.com/enkaust/status/1151805582556352513?ref_src=twsrc%5Etfw">July 18, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20181204 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>わかんなかったとこは, 捏造した <a href="https://t.co/MPDLpSVi1Q">pic.twitter.com/MPDLpSVi1Q</a></p>&mdash; 一人 (@nasu_zoi) <a href="https://twitter.com/nasu_zoi/status/1069800047636856832?ref_src=twsrc%5Etfw">2018年12月4日</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);

// char 2
export const T20210812 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>OC/3 <a href="https://t.co/0h7ue62dgP">pic.twitter.com/0h7ue62dgP</a></p>&mdash; 墨幽 (mӑk qjằv) (@sumiQj) <a href="https://twitter.com/sumiQj/status/1425831886060802056?ref_src=twsrc%5Etfw">August 12, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20210822 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>なめ <a href="https://t.co/p5KpAURnLU">pic.twitter.com/p5KpAURnLU</a></p>&mdash; sumi, peisithanatos (@enkaust) <a href="https://twitter.com/enkaust/status/1429464857263239174?ref_src=twsrc%5Etfw">August 22, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20211212 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>sumiくん(<a href="https://twitter.com/enkaust?ref_src=twsrc%5Etfw">@enkaust</a> )のOC勝手に描いて叩きつけた <a href="https://t.co/iJZZ14GbJg">pic.twitter.com/iJZZ14GbJg</a></p>&mdash; PEROLI (@p_eroli) <a href="https://twitter.com/p_eroli/status/1469924091708993536?ref_src=twsrc%5Etfw">December 12, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20211213 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>侖 <a href="https://t.co/ShNiKtYAXR">pic.twitter.com/ShNiKtYAXR</a></p>&mdash; 初夏の夜風の涼しさ (@enkaust) <a href="https://twitter.com/enkaust/status/1470417761612734465?ref_src=twsrc%5Etfw">December 13, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20211229 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://twitter.com/hashtag/OC?src=hash&amp;ref_src=twsrc%5Etfw">#OC</a> <a href="https://t.co/nzYgsb8PVO">pic.twitter.com/nzYgsb8PVO</a></p>&mdash; sumi, peisithanatos (@enkaust) <a href="https://twitter.com/enkaust/status/1476165285476708353?ref_src=twsrc%5Etfw">December 29, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20220102 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://twitter.com/hashtag/lewd?src=hash&amp;ref_src=twsrc%5Etfw">#lewd</a> 侖 揷入直前 <a href="https://t.co/U3g6vkaTX3">pic.twitter.com/U3g6vkaTX3</a></p>&mdash; 墨 (sumi) (@enkaust) <a href="https://twitter.com/enkaust/status/1477480446657437700?ref_src=twsrc%5Etfw">January 2, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20220106 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>未定 <a href="https://t.co/5jStU5pHJ6">pic.twitter.com/5jStU5pHJ6</a></p>&mdash; 雪㠀 墨 (йукисима суми) (@enkaust) <a href="https://twitter.com/enkaust/status/1479083414209048578?ref_src=twsrc%5Etfw">January 6, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20220117 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p><a href="https://twitter.com/hashtag/lewd?src=hash&amp;ref_src=twsrc%5Etfw">#lewd</a> 侖 ぶっかけ <a href="https://t.co/OWiqyXstEs">pic.twitter.com/OWiqyXstEs</a></p>&mdash; 雪㠀墨 (@enkaust) <a href="https://twitter.com/enkaust/status/1483129180187672577?ref_src=twsrc%5Etfw">January 17, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);
export const T20220131 = () => (<><blockquote className="twitter-tweet" data-theme="dark"><p>進捗 <a href="https://t.co/WMHf3qTyrY">pic.twitter.com/WMHf3qTyrY</a></p>&mdash; 雪㠀 墨 (@enkaust) <a href="https://twitter.com/enkaust/status/1488170066613272577?ref_src=twsrc%5Etfw">January 31, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></>);

